install.packages("rebird")
devtools::install_github("ropensci/rebird")
library("rebird")
library("dplyr")
Sys.setenv(EBIRD_KEY = 'nomj3kr577l9')
species_code('Tetrao urogallus')
a <-nearestobs(species = species_code('Tetrao urogallus'), lat = 49, lng = 13)
rebird:::tax
new_tax <- ebirdtaxonomy()
new_tax_auerhahn <- filter(new_tax, sciName =='Tetrao urogallus')
ebirdgeo(species = species_code('Haliaeetus albicilla'), lat = 49, lng = 13)
b <-nearestobs(species = species_code('Haliaeetus albicilla'), lat = 49, lng = 13)
ebirdregion(loc = 'GER', species = 'wescap1')
GER <- ebirdnotable(lat = 49, lng = 13)
remotes::install_github("CornellLabofOrnithology/auk")
